### ISSUE TITLE
error miguel 1

### ISSUE THREAD

**Issue by Miguel-J** [Aulla/pineboo#30]
lrelease warning: For some reason, i cannot save 'c:\pineboo\tempdata\cache\empresa\flfactppal\file.ts\flfactppal.es\247B2D8E4DD881FF7167EB72880B59EF23C2CC08.qm'

WARN: Not yet impl.: readState(<pineboolib.main.Project>) -> None

 File "c:\pineboo\pineboolib\main.py", line 282, in run

   self.readState()

Traceback (most recent call last):

 File "pineboo.py", line 338, in <module>

   ret = main()

 File "pineboo.py", line 253, in main

   project.run()

 File "c:\pineboo\pineboolib\main.py", line 284, in run

   self.acl_.init_()

 File "c:\pineboo\pineboolib\fllegacy\FLAccessControlLists.py", line 74, in init_

   self.init_(self._prj.conn.managerModules().content("acl.xml"))

 File "c:\pineboo\pineboolib\fllegacy\FLAccessControlLists.py", line 102, in init_

   ac =  FLAccessControlFactory().create(e.tagName())

 File "c:\pineboo\pineboolib\decorators.py", line 51, in newfn

   ret = fn(*args,**kwargs)

 File "c:\pineboo\pineboolib\fllegacy\FLAccessControlFactory.py", line 31, in create

   return FLAccessControlMainWindow()

 File "c:\pineboo\pineboolib\fllegacy\FLAccessControlFactory.py", line 59, in __init__

   super(FLAccessControlForm, self).__init__()

TypeError: super(type, obj): obj must be an instance or subtype of type

c:\pineboo>

**Comment by Aulla** [comment]
Es porque la parte de control de acceso para mainWindows está escrita pero no probada. Corregido error. Supongo que saldrán mas errores por estos lares
